name: SOFAServerless Runtime Unit Test
run-name: ${{ github.actor }} pushed code

on:
  push:
    branches:
      - master
    paths:
      - 'sofa-serverless-runtime/**'
      
  pull_request:
    branches:
      - master
    paths:
      - 'sofa-serverless-runtime/**'
      
  # enable manually running the workflow
  workflow_dispatch:

env:
  WORK_DIR: sofa-serverless-runtime

defaults:
  run:
    working-directory: sofa-serverless-runtime

jobs:
  unit-test-for-jdk17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: maven

      - name: Test
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -U
          && sh ./check_format.sh
          && mvn test

      - name: upload coverage reports to Codecov with github action
        uses: codecov/codecov-action@v3
